kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
nodes:
- role: control-plane
  kubeadmConfigPatches:
  - |
    kind: ClusterConfiguration
    apiServer:
      extraArgs:
        oidc-issuer-url: https://172.18.0.2:32000
        oidc-client-id: default
        oidc-ca-file: /etc/kubernetes/pki/apiserver.crt
        oidc-username-claim: email
        oidc-username-prefix: "oidc:"
        oidc-groups-claim: groups
        oidc-groups-prefix: "oidc:"
